def display_menu():
    print("Please select an option from the menu:")
    print("-" * 40)
    print("1. Option 1")
    print("2. Option 2")
    print("3. Option 3")
    print("4. Option 4")
    print("5. Option 5")
    print("6. Option 6")
    print("7. Option 7")
    print("8. Option 8")
    print("9. Option 9")
    print("0. Quit")
    print("-" * 40)